const $ = (selector) => document.querySelector(selector);
let state = { policies: [], claims: [] };
const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
const date = (value) => new Date(`${value}T12:00:00`).toLocaleDateString('pt-BR');
const api = async (url, options = {}) => { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível concluir a operação.'); return data; };
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 3000); }
function badge(status) { return `<span class="badge ${status.replace(' ', '_')}">${status.replace('_', ' ')}</span>`; }
function policyBody(form) { const body = new URLSearchParams(new FormData(form)); document.querySelectorAll('#policy-form input[name="cover"]').forEach(input => body.set(`cover_${input.value}`, input.checked)); return body; }
async function refresh() { try { state = await api('/api/state'); render(); await renderLedger(); } catch (error) { toast(`Servidor indisponível: ${error.message}`); } }
function render() {
  const { policies, claims } = state;
  $('#metric-policies').textContent = policies.filter(p => p.status === 'ATIVA').length;
  $('#metric-pending').textContent = claims.filter(c => c.status === 'EM_ANALISE').length;
  $('#metric-paid').textContent = money(claims.filter(c => c.status === 'PAGO').reduce((sum, c) => sum + c.amount, 0));
  $('#policies-empty').hidden = policies.length > 0;
  $('#policies-body').innerHTML = policies.map(p => `<tr><td><strong>#${p.id}</strong><small>Emitida no servidor local</small></td><td><strong>${p.client}</strong><small>${p.vehicle} · ${p.plate}</small></td><td class="cover">${p.covers.join(' · ')}</td><td>${date(p.start)}<small>até ${date(p.end)}</small></td><td>${badge(p.status)}</td><td><button class="button secondary table-action" onclick="openClaimFor('${p.id}')">Abrir sinistro</button></td></tr>`).join('');
  $('#claims-empty').hidden = claims.length > 0;
  $('#claims-body').innerHTML = claims.map(c => `<tr><td><strong>#${c.id}</strong><small>${c.client}</small></td><td>#${c.policyId}</td><td><strong>${c.type}</strong><small>${date(c.date)}</small></td><td>${money(c.amount)}</td><td>${badge(c.status)}</td><td>${c.status === 'EM_ANALISE' ? `<button class="button primary table-action" onclick="analyse('${c.id}')">Analisar</button>` : c.status === 'APROVADO' ? `<button class="button primary table-action" onclick="pay('${c.id}')">Registrar pagamento</button>` : `<button class="button secondary table-action" onclick="details('${c.id}')">Ver decisão</button>`}</td></tr>`).join('');
  const pending = claims.find(c => c.status === 'EM_ANALISE'); $('#action-title').textContent = pending ? `Sinistro #${pending.id} aguarda análise` : 'Nenhuma pendência'; $('#action-description').textContent = pending ? 'Execute o Smart Contract Java para aplicar as regras da apólice.' : 'Abra um sinistro para iniciar uma análise automatizada.'; $('#action-link').textContent = pending ? 'Analisar agora' : 'Ver sinistros'; $('#action-link').onclick = pending ? () => analyse(pending.id) : null;
}
async function renderLedger() { const ledger = await api('/api/ledger'); $('.chain-state').innerHTML = `<span class="dot"></span> ${ledger.valid ? 'Cadeia íntegra' : 'Cadeia inválida'}`; $('#ledger').innerHTML = ledger.blocks.slice().reverse().map(b => `<article class="event"><div class="event-icon">${b.index === 0 ? '◈' : '#' + b.index}</div><div><strong>${b.index === 0 ? 'Bloco gênesis' : b.data.split(' | ')[0].replaceAll('_', ' ')}</strong><p>${b.index === 0 ? 'Origem da cadeia local' : b.data}</p><small class="hash">Anterior: ${b.previousHash.slice(0, 20)}…</small></div><span class="hash">${b.hash.slice(0, 20)}…</span></article>`).join(''); }
function populatePolicySelect(selected) { $('#claim-policy').innerHTML = state.policies.filter(p => p.status === 'ATIVA').map(p => `<option value="${p.id}" ${p.id === selected ? 'selected' : ''}>#${p.id} · ${p.client} · ${p.vehicle}</option>`).join(''); }
window.openClaimFor = (id) => { populatePolicySelect(id); $('#claim-modal').showModal(); };
window.analyse = async (id) => { try { await api(`/api/claims/${id}/analyse`, { method: 'POST' }); await refresh(); showAnalysis(state.claims.find(c => c.id === id)); toast('Decisão registrada pelo Smart Contract e na blockchain.'); } catch (error) { toast(error.message); } };
window.pay = async (id) => { try { await api(`/api/claims/${id}/pay`, { method: 'POST' }); await refresh(); $('#analysis-modal').close(); toast('Pagamento registrado em um novo bloco local.'); } catch (error) { toast(error.message); } };
window.details = (id) => showAnalysis(state.claims.find(c => c.id === id));
function showAnalysis(claim) { const approved = claim.status !== 'REJEITADO'; $('#analysis-content').innerHTML = `<div class="modal-head"><div><p class="eyebrow">DECISÃO DO SMART CONTRACT</p><h2>Sinistro #${claim.id}</h2></div><button class="icon-button" onclick="this.closest('dialog').close()">×</button></div><div class="analysis-result ${approved ? 'ok' : 'no'}"><strong>${approved ? '✓ APROVADO' : '× REJEITADO'}</strong><p>${claim.reason || 'Aguardando execução das regras.'}</p></div><h3>Regras executadas no servidor</h3><ul class="rules"><li class="pass">✓ Existência e vigência da apólice</li><li class="pass">✓ Cobertura para a ocorrência</li><li class="pass">✓ Limite do valor segurado</li></ul><p class="hint">A decisão é gravada pela classe Blockchain do projeto e pode ser auditada abaixo.</p><div class="modal-actions"><button class="button secondary" onclick="this.closest('dialog').close()">Fechar</button>${claim.status === 'APROVADO' ? `<button class="button primary" onclick="pay('${claim.id}')">Registrar pagamento</button>` : ''}</div>`; $('#analysis-modal').showModal(); }
document.querySelectorAll('[data-open]').forEach(button => button.addEventListener('click', () => { if (button.dataset.open === 'claim-modal') { if (!state.policies.some(p => p.status === 'ATIVA')) return toast('Emita uma apólice ativa antes de abrir um sinistro.'); populatePolicySelect(); } $(`#${button.dataset.open}`).showModal(); }));
$('#policy-form').addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget; if (form.end.value < form.start.value) return toast('A data final deve ser posterior à inicial.'); try { await api('/api/policies', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: policyBody(form) }); form.reset(); $('#policy-modal').close(); await refresh(); toast('Apólice emitida com sucesso.'); } catch (error) { toast(error.message); } });
$('#claim-form').addEventListener('submit', async event => { event.preventDefault(); try { await api('/api/claims', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams(new FormData(event.currentTarget)) }); event.currentTarget.reset(); $('#claim-modal').close(); await refresh(); toast('Sinistro aberto e encaminhado para análise.'); } catch (error) { toast(error.message); } });
const today = new Date().toISOString().slice(0, 10); document.querySelectorAll('input[type=date]').forEach(input => input.value = today); refresh();
